### ISSUE TITLE
OSError: SavedModel file does not exist at: birds.h5/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by skysty** [manideepc/Bird-Species-Identifiaction-from-Image#1]
Hello Friend! i want to use your template for indentification bird species from image but  shows this  problem   
OSError: SavedModel file does not exist at: birds.h5/{saved_model.pbtxt|saved_model.pb}
how to resolve  it please

**Comment by manideepc** [comment]
Hi ,
Version 1.1.py
<https://github.com/manideepc/Bird-Species-Identifiaction-from-Image/blob/master/Version%201.1.py>
run this file in repo.
In the last line Change the Model.save() to 'Birds.h5'.

Thanks
Manideep

**Comment by manideepc** [comment]
Please don't forget to give Star to my Repo.
Cheers
Manideep
